default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails
  password: rails
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: star_money_development
test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  database: star_money_production

